### ISSUE TITLE
i installed as said but nothing happens?

### ISSUE THREAD

**Issue by gizmoninji** [OndrejNepozitek/PlateUpMods#2]
wondering if theres something missing. anyone can help?

**Comment by OndrejNepozitek** [comment]
Hello! 

- Did you install both the BepInEx mod loader and the mod itself?
- Can you check that the folders look like in the guide? https://plateuptools.com/kitchen-designer/how-to-install
- If you run the game, does an additional console window appear?
- If the console window appears, are there any errors?

**Comment by gizmoninji** [comment]
so i did check . eveyrthing looks like exactly like the photo. but i just now got it to work. someone helped me do it properly. there was a step that i didnt do correctly.

**Comment by gizmoninji** [comment]
thnk you for responding. your awesome

**Comment by OndrejNepozitek** [comment]
Just curious - what was the problem? So that I can maybe improve the instructions.

**Comment by DevourHearts** [comment]
I too would have liked to know what was done incorrectly. I have installed and uninstalled at least 5 times. The only difference between my folder and the instruction folder is that mine is missing the winhttp.dll app extension in my game folder. I looked to see if I needed to actually install the BepInEx but I did not see anything.

**Comment by OndrejNepozitek** [comment]
> I too would have liked to know what was done incorrectly. I have installed and uninstalled at least 5 times. The only difference between my folder and the instruction folder is that mine is missing the winhttp.dll app extension in my game folder. I looked to see if I needed to actually install the BepInEx but I did not see anything.

Hello, you actually need the `winhttp.dll` file because that's the one that makes it possible to load the mod loader (bepinex) and the loader then loads Kitchen Designer. It's possible that your antivirus is blocking that file because it should be in the zip archive that includes BepInEx. The file can probably be a false positive for some antivirus programs because it does something a bit weird as it can load other programs that can be executed before the game itself.
